name: Build Rocket

on:
  pull_request:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Permissions
      run: chmod +x ./gradlew
    - name: Build Dev
      run: ./gradlew build
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: build/libs/**
