name: Rocket Nightly

on:
  schedule:
    - cron: 0 0 * * * # daily
  workflow_dispatch:

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Permissions
      run: chmod +x ./gradlew
    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 'wrapper' 
    - name: Build Dev
      run: ./gradlew jar
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-reports
        path: build/libs/**
